### PR TITLE
Support gomodules

### PR DESCRIPTION
**Pull request by MelleKoning**
This PR is to support go modules

Is the `release` branch really the default branch, or should I move the PR to merge into the master branch? I'm confused :)

Benefit:
- source can be checked out outside of GOPATH
- dependend modules are in go.mod and downloaded in the /vendor folder
- Updates can be down with usual `go mod download` `go mod vendor` commands

### CODE REVIEW

**Comment by Tilps** [comment]
release branch is default - all PRs should however be vs master :P

**Comment by Tilps** [comment]
I don't think we should be committing the vendor directory to source control though...

**Comment by MelleKoning** [comment]
Although I also was against committing depending modules, this is how go wants it to be backwards compatible with older versions of go.


The depended modules van easily be updated by updating the reference in go.mod and the 'go mod vendor' command.

We could omit vendoring, but the depended modules are not yet go.mod enabled.

Text from https://golang.org/ref/mod

"Vendoring ¶
When using modules, the go command typically satisfies dependencies by downloading modules from their sources into the module cache, then loading packages from those downloaded copies. Vendoring may be used to allow interoperation with older versions of Go, or to ensure that all files used for a build are stored in a single file tree."

I think we can include it now for backwards compatibility and remove the vendor folder later. This is probably easier for devs trying this repository, what do you think?

**Comment by MelleKoning** [comment]
PS: the line in go.mod with "replace" is needed to support forks. Otherwise could not build the forked repository.

**Comment by MelleKoning** [comment]
Alternative supplied in #153

**Pull request merged**
