### PR TITLE
Force match play to use multiplex backend to match selfplay so backend-opts apply evenly

### PR DESCRIPTION
**Pull request by Tilps**

### CODE REVIEW

**Comment by ankan-ban** [comment]
can you also fix this typo:
				switch word {
					case "", "--backend", "tf", "cudnn", "opencl", "blas", "cudnn-fp",
should be **cudnn-fp16**

**Comment by Tilps** [comment]
@ankan-ban That logic isn't in the code anymore in mater, only in release branch.

**Comment by borg323** [comment]
The "cudnn-fp" was not a typo, the numbers were stripped during tokenization. But this is moot now. Regarding the rest of the patch, my understanding is that multiplexing is the default for selfplay, so do we need it?

**Comment by Tilps** [comment]
the patch is for mode != selfplay
multiplexing is only the default for selfplay - but our backend-opts are always the same and so we should use multiplexing always.

**Comment by Tilps** [comment]
Tested had a successful match game using multiplexing.

**Comment by sergiovieri** [comment]
does it accept backend-opts? (fp16 and which gpu)

**Comment by borg323** [comment]
@sergiovieri the version in the master branch has the `--backend-opts` that is passed directly to lc0 (after some minor checks). The `--lc0args` method can still be used, but will be discouraged.

**Comment by mooskagh** [comment]
I'm fine with fp16 in training and match games!

**Pull request merged**
