### PR TITLE
add keep option

### PR DESCRIPTION
**Pull request by borg323**
This was requested on discord. Just adds an option to keep all downloaded networks.

### CODE REVIEW

**Comment by borg323** [comment]
I am considering an additional patch <https://github.com/borg323/lczero-client/commit/a8ee411f14c99fb2b059b04f3a1b9b705e433ee0> on top of this that adds a `--keep-time` option that only deletes networks older than the specified time. I'm not sure whether this should be an additional option, or have only one option or just have a default retention time, so I'm making only this pr and waiting for feedback.

**Comment by Tilps** [comment]
I think I would be happy with just the keep time flag - I assume it supports --keep-time=1y

**Comment by borg323** [comment]
Unfortunately no, only up to hours are supported: `Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h"`, see <https://golang.org/pkg/time/#ParseDuration>.

**Comment by Tilps** [comment]
okay, I think both flags make sense then.

**Pull request merged**
